Project2: Instantiation.o
	g++ -o Project2 Instantiation.o

Instantiation.o: Instantiation.cpp
	g++ -c -Wall -std=c++11 Instantiation.cpp -g
clean:
	rm -f Project2 Instantiation.o
rebuild:
	make clean
	make
