Lab: Instantiation.o
	g++ -o Lab Instantiation.o

Instantiation.o: Instantiation.cpp
	g++ -c -Wall -std=c++11 Instantiation.cpp -g
clean:
	rm -f Lab Instantiation.o
rebuild:
	make clean
	make
